### ISSUE TITLE
v0.2.2 dependences with problem

### ISSUE THREAD

**Issue by kapt4inw01f** [openzipkin/zipkin-go#163] opened 2020-06-16 03:20 UTC
github.com/openzipkin/zipkin-go@v0.2.2 requires
        github.com/golang/snappy@v0.0.0-20180518054509-2e65f85255db: invalid version: git fetch --unshallow -f https://github.com/golang/snappy in /data/go/pkg/mod/cache/vcs/bd5478a77a28a7d755c9e7a8b339db5eab8981ed54642194facc07ec0db93053

maybe snappy has deleted the tag v0.0.0-20180518054509-2e65f85255db

**Comment by jcchavezs** [comment] 2020-08-11 08:14
I am curious about this not failing in travis CI. Do you have a list of steps to reproducing this error?

**Comment by basvanbeek** [comment] 2020-09-09 10:13
Closing as we can't reproduce without more details. Feel free to re-open if new information is available.

**Closed by basvanbeek** 2020-09-09 10:13 UTC
